---
- name: Create a directory and copy files into it
  hosts: all
  tasks: 
    - name: Create a directory
      file:
        name: /tmp/folder123
        state: directory
    - name: copy files
      copy:
        src: /etc/passwd
        dest: /tmp/folder123

...
