---
- name: Download jenkins.war and change permissions
  hosts: all
  tasks:
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.479.3/jenkins.war
        dest: /tmp
    - name: Change permission of jenkins.war file
      file:
        name: /tmp/jenkins.war
        mode: 760
        owner: Ravi
        group: Sony




...
